extends: spectral:oas
overrides:
  - files:
      - "specs/components.yaml"
    rules:
      oas3-api-servers: off
      info-description: off
      info-contact: off
      oas3-unused-component: off
