extends: spectral:oas
overrides:
  - files:
      - "specs/components.yaml"
    rules:
      oas3-api-servers: off
      info-description: off
      info-contact: off
      oas3-unused-component: off
  - files:
      - "specs/my.yaml"
    rules:
      oas3-schema: off  # QUERY is a valid RFC 10008 method, but Spectral doesn't know it
