// Generated by scripts/scrape-news.mjs on 2026-09-04 — do not edit by hand.
import { type TokenomicsModel } from "./seed"

export const newsModels: TokenomicsModel[] = [
  {
    "id": "news-gpt-oss-20b",
    "name": "Gpt-Oss-20b",
    "providerId": "openai",
    "family": "gpt-oss",
    "description": "",
    "status": "active",
    "contextWindow": 0,
    "maxOutputTokens": 0,
    "modalities": {
      "input": [
        "text"
      ],
      "output": [
        "text"
      ]
    },
    "pricing": [
      {
        "inputPricePer1M": 0.41,
        "outputPricePer1M": 1.3,
        "currency": "USD",
        "effectiveDate": "2026-09-04",
        "source": "https://github.com/tokencanopy/price"
      }
    ],
    "tags": [
      "news"
    ]
  }
]
