export interface ProviderSeed {
  id: string; name: string; description: string; website: string; country_code: string; founded_date: string; status: string
}
export interface ModelSeed {
  id: string; name: string; family: string; provider_id: string; description: string; model_type: string; release_date: string; status: string; predecessor_ids: string; successor_ids: string; tags: string
}
export interface EventSeed {
  id: string; event_type: string; event_date: string; title: string; description: string; provider_id: string; model_id?: string; source_url?: string; source_type?: string; metadata?: string; tags?: string
}

export const providers: ProviderSeed[] = [
  { id: "openai", name: "OpenAI", description: "AI research and deployment company.", website: "https://openai.com", country_code: "US", founded_date: "2015-12-11", status: "active" },
  { id: "anthropic", name: "Anthropic", description: "AI safety company building reliable AI systems.", website: "https://anthropic.com", country_code: "US", founded_date: "2021-01-01", status: "active" },
  { id: "google", name: "Google DeepMind", description: "AI research division of Alphabet.", website: "https://deepmind.google", country_code: "GB", founded_date: "2010-09-01", status: "active" },
  { id: "meta", name: "Meta AI", description: "AI research division of Meta.", website: "https://ai.meta.com", country_code: "US", founded_date: "2013-12-01", status: "active" },
  { id: "mistral", name: "Mistral AI", description: "French AI company building open models.", website: "https://mistral.ai", country_code: "FR", founded_date: "2023-04-01", status: "active" },
  { id: "deepseek", name: "DeepSeek", description: "Chinese AI company focused on foundation models.", website: "https://deepseek.com", country_code: "CN", founded_date: "2023-01-01", status: "active" },
]

export const models: ModelSeed[] = [
  { id: "gpt-4", name: "GPT-4", family: "GPT", provider_id: "openai", description: "Large multimodal model with improved reasoning.", model_type: "llm", release_date: "2023-03-14", status: "active", predecessor_ids: '["gpt-3.5"]', successor_ids: '["gpt-4-turbo","gpt-4o"]', tags: "[]" },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo", family: "GPT", provider_id: "openai", description: "Faster and cheaper GPT-4 with updated knowledge.", model_type: "llm", release_date: "2023-11-06", status: "active", predecessor_ids: '["gpt-4"]', successor_ids: '["gpt-4o"]', tags: "[]" },
  { id: "gpt-4o", name: "GPT-4o", family: "GPT", provider_id: "openai", description: "Omnimodal flagship model with native audio and image.", model_type: "multimodal", release_date: "2024-05-13", status: "active", predecessor_ids: '["gpt-4-turbo"]', successor_ids: '["gpt-5"]', tags: '["multimodal","flagship"]' },
  { id: "gpt-4o-mini", name: "GPT-4o Mini", family: "GPT", provider_id: "openai", description: "Smaller and cheaper GPT-4o for lightweight tasks.", model_type: "llm", release_date: "2024-07-18", status: "active", predecessor_ids: "[]", successor_ids: "[]", tags: "[]" },
  { id: "o1", name: "o1", family: "o-series", provider_id: "openai", description: "Reasoning model with chain-of-thought.", model_type: "llm", release_date: "2024-09-12", status: "active", predecessor_ids: "[]", successor_ids: "[]", tags: '["reasoning"]' },
  { id: "o3", name: "o3", family: "o-series", provider_id: "openai", description: "Advanced reasoning model.", model_type: "llm", release_date: "2025-01-01", status: "active", predecessor_ids: '["o1"]', successor_ids: "[]", tags: '["reasoning"]' },
  { id: "gpt-5", name: "GPT-5", family: "GPT", provider_id: "openai", description: "Next-generation GPT model.", model_type: "llm", release_date: "2025-06-01", status: "active", predecessor_ids: '["gpt-4o"]', successor_ids: "[]", tags: "[]" },
  { id: "claude-3-opus", name: "Claude 3 Opus", family: "Claude 3", provider_id: "anthropic", description: "Most capable Claude model.", model_type: "llm", release_date: "2024-03-04", status: "active", predecessor_ids: '["claude-2"]', successor_ids: '["claude-3.5-sonnet"]', tags: "[]" },
  { id: "claude-3-sonnet", name: "Claude 3 Sonnet", family: "Claude 3", provider_id: "anthropic", description: "Balanced Claude model.", model_type: "llm", release_date: "2024-03-04", status: "active", predecessor_ids: "[]", successor_ids: '["claude-3.5-sonnet"]', tags: "[]" },
  { id: "claude-3-haiku", name: "Claude 3 Haiku", family: "Claude 3", provider_id: "anthropic", description: "Fast and cheap Claude model.", model_type: "llm", release_date: "2024-03-13", status: "active", predecessor_ids: "[]", successor_ids: "[]", tags: "[]" },
  { id: "claude-3.5-sonnet", name: "Claude 3.5 Sonnet", family: "Claude 3.5", provider_id: "anthropic", description: "Mid-tier Claude with improved performance.", model_type: "llm", release_date: "2024-06-20", status: "active", predecessor_ids: '["claude-3-opus","claude-3-sonnet"]', successor_ids: '["claude-4-sonnet"]', tags: "[]" },
  { id: "claude-4-sonnet", name: "Claude 4 Sonnet", family: "Claude 4", provider_id: "anthropic", description: "Latest Claude model.", model_type: "llm", release_date: "2025-02-01", status: "active", predecessor_ids: '["claude-3.5-sonnet"]', successor_ids: "[]", tags: "[]" },
  { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro", family: "Gemini", provider_id: "google", description: "Mid-size Gemini with long context.", model_type: "multimodal", release_date: "2024-02-15", status: "active", predecessor_ids: '["gemini-1.0-pro"]', successor_ids: '["gemini-2.0-pro"]', tags: "[]" },
  { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash", family: "Gemini", provider_id: "google", description: "Fast and efficient Gemini.", model_type: "multimodal", release_date: "2024-05-14", status: "active", predecessor_ids: "[]", successor_ids: '["gemini-2.0-flash"]', tags: "[]" },
  { id: "gemini-2.0-pro", name: "Gemini 2.0 Pro", family: "Gemini", provider_id: "google", description: "Updated Gemini Pro model.", model_type: "multimodal", release_date: "2025-02-01", status: "active", predecessor_ids: '["gemini-1.5-pro"]', successor_ids: "[]", tags: "[]" },
  { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", family: "Gemini", provider_id: "google", description: "Updated Gemini Flash model.", model_type: "multimodal", release_date: "2025-02-01", status: "active", predecessor_ids: '["gemini-1.5-flash"]', successor_ids: "[]", tags: "[]" },
  { id: "llama-3-8b", name: "Llama 3 8B", family: "Llama 3", provider_id: "meta", description: "Open-source 8B parameter model.", model_type: "llm", release_date: "2024-04-18", status: "active", predecessor_ids: '["llama-2-7b"]', successor_ids: '["llama-3.1-8b"]', tags: '["open-source"]' },
  { id: "llama-3-70b", name: "Llama 3 70B", family: "Llama 3", provider_id: "meta", description: "Open-source 70B parameter model.", model_type: "llm", release_date: "2024-04-18", status: "active", predecessor_ids: '["llama-2-70b"]', successor_ids: '["llama-3.1-70b"]', tags: '["open-source"]' },
  { id: "llama-3.1-8b", name: "Llama 3.1 8B", family: "Llama 3.1", provider_id: "meta", description: "Updated open-source 8B model.", model_type: "llm", release_date: "2024-07-23", status: "active", predecessor_ids: '["llama-3-8b"]', successor_ids: "[]", tags: '["open-source"]' },
  { id: "llama-3.1-70b", name: "Llama 3.1 70B", family: "Llama 3.1", provider_id: "meta", description: "Updated open-source 70B model.", model_type: "llm", release_date: "2024-07-23", status: "active", predecessor_ids: '["llama-3-70b"]', successor_ids: "[]", tags: '["open-source"]' },
  { id: "llama-3.1-405b", name: "Llama 3.1 405B", family: "Llama 3.1", provider_id: "meta", description: "Largest open-source model.", model_type: "llm", release_date: "2024-07-23", status: "active", predecessor_ids: "[]", successor_ids: "[]", tags: '["open-source"]' },
  { id: "mistral-7b", name: "Mistral 7B", family: "Mistral", provider_id: "mistral", description: "Efficient 7B parameter model.", model_type: "llm", release_date: "2023-09-27", status: "active", predecessor_ids: "[]", successor_ids: '["mixtral-8x7b"]', tags: '["open-source"]' },
  { id: "mixtral-8x7b", name: "Mixtral 8x7B", family: "Mixtral", provider_id: "mistral", description: "Mixture of experts model.", model_type: "llm", release_date: "2023-12-11", status: "active", predecessor_ids: '["mistral-7b"]', successor_ids: '["mistral-large"]', tags: '["moex"]' },
  { id: "mistral-large", name: "Mistral Large", family: "Mistral", provider_id: "mistral", description: "Mistral's most capable model.", model_type: "llm", release_date: "2024-02-26", status: "active", predecessor_ids: '["mixtral-8x7b"]', successor_ids: "[]", tags: "[]" },
  { id: "deepseek-v2", name: "DeepSeek V2", family: "DeepSeek", provider_id: "deepseek", description: "Efficient MoE architecture model.", model_type: "llm", release_date: "2024-05-06", status: "active", predecessor_ids: "[]", successor_ids: '["deepseek-r1"]', tags: '["moex"]' },
  { id: "deepseek-r1", name: "DeepSeek R1", family: "DeepSeek", provider_id: "deepseek", description: "Reasoning-focused model.", model_type: "llm", release_date: "2025-01-20", status: "active", predecessor_ids: '["deepseek-v2"]', successor_ids: "[]", tags: '["reasoning"]' },
]

export const events: EventSeed[] = [
  { id: "evt_openai_founded", event_type: "provider_created", event_date: "2015-12-11", title: "OpenAI Founded", description: "OpenAI was founded as a non-profit AI research company.", provider_id: "openai", source_url: "https://openai.com/about", source_type: "documentation" },
  { id: "evt_anthropic_founded", event_type: "provider_created", event_date: "2021-01-01", title: "Anthropic Founded", description: "Anthropic founded by former OpenAI researchers.", provider_id: "anthropic", source_url: "https://anthropic.com/about", source_type: "documentation" },
  { id: "evt_deepmind_founded", event_type: "provider_created", event_date: "2010-09-01", title: "DeepMind Founded", description: "DeepMind was founded as an AI research lab.", provider_id: "google", source_type: "documentation" },
  { id: "evt_mistral_founded", event_type: "provider_created", event_date: "2023-04-01", title: "Mistral AI Founded", description: "Mistral AI founded in France.", provider_id: "mistral", source_url: "https://mistral.ai/about", source_type: "announcement" },
  { id: "evt_deepseek_founded", event_type: "provider_created", event_date: "2023-01-01", title: "DeepSeek Founded", description: "DeepSeek founded as a Chinese AI research company.", provider_id: "deepseek", source_type: "documentation" },
  { id: "evt_gpt4_release", event_type: "model_released", event_date: "2023-03-14", title: "GPT-4 Released", description: "OpenAI released GPT-4, a large multimodal model.", provider_id: "openai", model_id: "gpt-4", source_url: "https://openai.com/index/gpt-4", source_type: "announcement" },
  { id: "evt_gpt4_turbo_release", event_type: "model_released", event_date: "2023-11-06", title: "GPT-4 Turbo Released", description: "OpenAI released GPT-4 Turbo at DevDay 2023.", provider_id: "openai", model_id: "gpt-4-turbo", source_url: "https://openai.com/index/new-models-and-developer-products-announced-at-devday-2023", source_type: "announcement" },
  { id: "evt_mixtral_release", event_type: "model_released", event_date: "2023-12-11", title: "Mixtral 8x7B Released", description: "Mistral released Mixtral 8x7B MoE model.", provider_id: "mistral", model_id: "mixtral-8x7b", source_url: "https://mistral.ai/news/mixtral-8x7b", source_type: "announcement" },
  { id: "evt_gemini15_release", event_type: "model_released", event_date: "2024-02-15", title: "Gemini 1.5 Pro Released", description: "Google released Gemini 1.5 Pro with 1M token context.", provider_id: "google", model_id: "gemini-1.5-pro", source_url: "https://blog.google/technology/ai/gemini-1.5", source_type: "announcement" },
  { id: "evt_mistral_large_release", event_type: "model_released", event_date: "2024-02-26", title: "Mistral Large Released", description: "Mistral released their most capable model.", provider_id: "mistral", model_id: "mistral-large", source_url: "https://mistral.ai/news/mistral-large", source_type: "announcement" },
  { id: "evt_claude3_release", event_type: "model_released", event_date: "2024-03-04", title: "Claude 3 Family Released", description: "Anthropic released Claude 3 Opus, Sonnet, and Haiku.", provider_id: "anthropic", model_id: "claude-3-opus", source_url: "https://anthropic.com/news/claude-3-family", source_type: "announcement" },
  { id: "evt_llama3_release", event_type: "model_released", event_date: "2024-04-18", title: "Llama 3 Released", description: "Meta released Llama 3 8B and 70B open-source models.", provider_id: "meta", model_id: "llama-3-8b", source_url: "https://ai.meta.com/blog/meta-llama-3", source_type: "announcement" },
  { id: "evt_deepseek_v2_release", event_type: "model_released", event_date: "2024-05-06", title: "DeepSeek V2 Released", description: "DeepSeek released V2 with MoE architecture.", provider_id: "deepseek", model_id: "deepseek-v2", source_url: "https://deepseek.com/blogs/deepseek-v2", source_type: "blog" },
  { id: "evt_gpt4o_release", event_type: "model_released", event_date: "2024-05-13", title: "GPT-4o Released", description: "OpenAI released GPT-4o with native multimodal capabilities.", provider_id: "openai", model_id: "gpt-4o", source_url: "https://openai.com/index/hello-gpt-4o", source_type: "announcement", metadata: '{"modalities":["text","image","audio"]}' },
  { id: "evt_claude35_sonnet_release", event_type: "model_released", event_date: "2024-06-20", title: "Claude 3.5 Sonnet Released", description: "Anthropic released Claude 3.5 Sonnet.", provider_id: "anthropic", model_id: "claude-3.5-sonnet", source_url: "https://anthropic.com/news/claude-3-5-sonnet", source_type: "announcement" },
  { id: "evt_llama31_release", event_type: "model_released", event_date: "2024-07-23", title: "Llama 3.1 Released", description: "Meta released Llama 3.1 8B, 70B, and 405B models.", provider_id: "meta", model_id: "llama-3.1-405b", source_url: "https://ai.meta.com/blog/meta-llama-3-1", source_type: "announcement" },
  { id: "evt_gpt4o_mini_release", event_type: "model_released", event_date: "2024-07-18", title: "GPT-4o Mini Released", description: "OpenAI released GPT-4o Mini for lightweight tasks.", provider_id: "openai", model_id: "gpt-4o-mini", source_type: "announcement" },
  { id: "evt_o1_release", event_type: "model_released", event_date: "2024-09-12", title: "o1 Reasoning Model Released", description: "OpenAI released o1 with chain-of-thought reasoning.", provider_id: "openai", model_id: "o1", source_url: "https://openai.com/index/introducing-openai-o1-preview", source_type: "announcement" },
  { id: "evt_deepseek_r1_release", event_type: "model_released", event_date: "2025-01-20", title: "DeepSeek R1 Released", description: "DeepSeek released R1 reasoning model.", provider_id: "deepseek", model_id: "deepseek-r1", source_type: "announcement" },
  { id: "evt_claude4_sonnet_release", event_type: "model_released", event_date: "2025-02-01", title: "Claude 4 Sonnet Released", description: "Anthropic released Claude 4 Sonnet.", provider_id: "anthropic", model_id: "claude-4-sonnet", source_url: "https://anthropic.com/news/claude-4-sonnet", source_type: "announcement" },
  { id: "evt_gemini20_release", event_type: "model_released", event_date: "2025-02-01", title: "Gemini 2.0 Released", description: "Google released Gemini 2.0 Pro and Flash.", provider_id: "google", model_id: "gemini-2.0-pro", source_url: "https://blog.google/technology/ai/gemini-2-0", source_type: "announcement" },
  { id: "evt_gpt5_release", event_type: "model_released", event_date: "2025-06-01", title: "GPT-5 Released", description: "OpenAI released GPT-5.", provider_id: "openai", model_id: "gpt-5", source_type: "announcement" },
  { id: "evt_gpt4o_context_update", event_type: "context_window_changed", event_date: "2024-08-01", title: "GPT-4o Context Expanded", description: "GPT-4o context window expanded.", provider_id: "openai", model_id: "gpt-4o", source_type: "release_notes" },
  { id: "evt_gpt4o_image_gen", event_type: "capability_added", event_date: "2024-10-01", title: "GPT-4o Gains Image Generation", description: "GPT-4o added native image generation.", provider_id: "openai", model_id: "gpt-4o", source_type: "release_notes", metadata: '{"capability":"image_generation"}' },
]
